### ISSUE TITLE
User can sort their entries by date created.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/code-journal#10]
## 💰 Motivation

Coders will want to sort entries by date created.

## 📐 Plan

Make the date in filter bar actually do something.

## ✅ Task List

- [x] Add two check boxes that can only have one or no checks to filter box (amended to be three radio buttons)
- [x] Add a time stamp to entry form
- [x] Update the form submit function to Include a timestamp with entries inside the data model
- [x] Modify the entry view update function to take a parameter called date with a default value of null
- [x] Modify the entry view update function to take a parameter called before with a default value of null
- [x] Create a function named search
- [x] Grab the values of the check boxes and see if the user wants entries before or after date, or neither (null), store this inside of a variable in search function.
- [x] Inside of search take all values of filter elements, and plug them into the function updateEntryView like this: updateEntryView(querystring,date,beforeorafter)
~~- [ ] Query the DOM for the date and store them in  variables~~
~~- [ ] Query the DOM for the check boxes and store them in  variables~~
Unnecessary since we have the form we can just access these through that
- [x] Add an input event handler to date to call search function
- [x] Modify the search box event handler to call the search function instead
- [ ] Modify the entry view update function to display only entries on a specific date if date is not null and before is null, otherwise if date is not null and before is true, show entries before date, otherwise show entries after that date.
