### ISSUE TITLE
User can add tags to an entry.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/code-journal#11]
## 💰 Motivation

Coders will want to add tags to entries to make searching easier

## 📐 Plan

Allow users to add tags inside the entry form

## ✅ Task List
- [ ] Update the data model to include an empty array called tags
- [ ] Add a new text field to the entry form
- [ ] Split the string in the text field in all caps delimited by spaces and assign that value to a variable.
- [ ] Remove all duplicate values inside that variable
- [ ] set the tags property of the entry to the variable
- [ ] Make sure edit function Includes all existing tags of edited entry inside of the text field when user wants to edit their entry.
- [ ] Modify submit function to Loop through the entry tags, and append all tags to the root of the data model if those tags are not in data.tags
