### ISSUE TITLE
User can filter entries by tag.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/code-journal#12]
## 💰 Motivation

Coders will want to filter entries by tag to make organization easier

## 📐 Plan

Allow users to filter items by tags

## ✅ Task List
- [ ] Add a flex container to the filter box.
- [ ] Query the DOM for the flex container
- [ ] Create a function that creates a scroll-able DOM tree of button elements with text content of existing tags
- [ ] Add on click event handlers to the buttons that append their tag to an array variable searchTags 
- [ ] Append the DOM tree to the container in step one
- [ ] modify the entry view update function to take an additional array parameter called tags with a default value of empty array, that filters entries containing all tags in the array as it's end step if tag is not null.
