### ISSUE TITLE
User can search their entries.

### ISSUE THREAD

**Issue by humbertovnavarro** [humbertovnavarro/code-journal#9]
## 💰 Motivation

Coders will want to search for entries if their entry lists are big.

## 📐 Plan

Create a search box that allows users to search for their entries

## ✅ Task 

- [x] Create a filter box inside of the entry data view
- [x] Inside of the filter box create a search input field
- [x] Attach a change event  handler to the search box that calls the entry update function with a string parameter based on the search field
- [x] Modify the entry view update function to include a string parameter with a default value of empty string
- [x] Modify the entry view update function to take a string as a parameter that displays only entries that have an index of that string.
